export const pokemonList = [
  { index: "1", name: "Bulbasaur", description: "Ini deskripsi untuk Bulbasaur. Bulbasaur adalah Pokemon tipe rumput dan beracun." },
  { index: "2", name: "Ivysaur", description: "Ini deskripsi untuk Ivysaur. Ivysaur adalah Pokemon tipe rumput dan beracun." },
  { index: "3", name: "Venusaur", description: "Ini deskripsi untuk Venusaur. Venusaur adalah Pokemon tipe rumput dan beracun." },
  { index: "4", name: "Charmander", description: "Ini deskripsi untuk Charmander. Charmander adalah Pokemon tipe api." },
  { index: "5", name: "Charmeleon", description: "Ini deskripsi untuk Charmeleon. Charmeleon adalah Pokemon tipe api." },
  { index: "6", name: "Charizard", description: "Ini deskripsi untuk Charizard. Charizard adalah Pokemon tipe api dan terbang." },
  { index: "7", name: "Squirtle", description: "Ini deskripsi untuk Squirtle. Squirtle adalah Pokemon tipe air." },
    { index: "8", name: "Wartortle", description: "Ini deskripsi untuk Wartortle. Wartortle adalah Pokemon tipe air." },
    { index: "9", name: "Blastoise", description: "Ini deskripsi untuk Blastoise. Blastoise adalah Pokemon tipe air." },
    { index: "10", name: "Caterpie", description: "Ini deskripsi untuk Caterpie. Caterpie adalah Pokemon tipe serangga." },
    { index: "11", name: "Metapod", description: "Ini deskripsi untuk Metapod. Metapod adalah Pokemon tipe serangga." },
    { index: "12", name: "Butterfree", description: "Ini deskripsi untuk Butterfree. Butterfree adalah Pokemon tipe serangga dan terbang." },
    { index: "13", name: "Weedle", description: "Ini deskripsi untuk Weedle. Weedle adalah Pokemon tipe serangga dan racun." },
    { index: "14", name: "Kakuna", description: "Ini deskripsi untuk Kakuna. Kakuna adalah Pokemon tipe serangga dan racun." },
    { index: "15", name: "Beedrill", description: "Ini deskripsi untuk Beedrill. Beedrill adalah Pokemon tipe serangga dan racun." },
    { index: "16", name: "Pidgey", description: "Ini deskripsi untuk Pidgey. Pidgey adalah Pokemon tipe normal dan terbang." },
    { index: "17", name: "Pidgeotto", description: "Ini deskripsi untuk Pidgeotto. Pidgeotto adalah Pokemon tipe normal dan terbang." },
    { index: "18", name: "Pidgeot", description: "Ini deskripsi untuk Pidgeot. Pidgeot adalah Pokemon tipe normal dan terbang." },
    { index: "19", name: "Rattata", description: "Ini deskripsi untuk Rattata. Rattata adalah Pokemon tipe normal." },
    { index: "20", name: "Raticate", description: "Ini deskripsi untuk Raticate. Raticate adalah Pokemon tipe normal." },
    { index: "21", name: "Spearow", description: "Ini deskripsi untuk Spearow. Spearow adalah Pokemon tipe normal dan terbang." },
    { index: "22", name: "Fearow", description: "Ini deskripsi untuk Fearow. Fearow adalah Pokemon tipe normal dan terbang." },
    { index: "23", name: "Ekans", description: "Ini deskripsi untuk Ekans. Ekans adalah Pokemon tipe racun." },
    { index: "24", name: "Arbok", description: "Ini deskripsi untuk Arbok. Arbok adalah Pokemon tipe racun." },
    { index: "25", name: "Pikachu", description: "Ini deskripsi untuk Pikachu. Pikachu adalah Pokemon tipe listrik." },
    { index: "26", name: "Raichu", description: "Ini deskripsi untuk Raichu. Raichu adalah Pokemon tipe listrik." },
    { index: "27", name: "Sandshrew", description: "Ini deskripsi untuk Sandshrew. Sandshrew adalah Pokemon tipe tanah." },
    { index: "28", name: "Sandslash", description: "Ini deskripsi untuk Sandslash. Sandslash adalah Pokemon tipe tanah." },
    { index: "29", name: "Nidoran♀", description: "Ini deskripsi untuk Nidoran♀. Nidoran♀ adalah Pokemon tipe racun." },
     { index: "30", name: "Nidorina", description: "Ini deskripsi untuk Nidorina. Nidorina adalah Pokemon tipe racun." },
];
